name: amicons
description: "Amicons is a Flutter icons hub that brings together popular icon sets in one place, including Iconly, Remix, Vuesax, Lucide, and Flaticon.With this package, there's no need to download multiple icon packages for a single projectâ€”simply install Amicons and gain access to all these icon sets effortlessly."
version: 0.0.1
author: "Ayush Maji"
homepage: https://github.com/AyushMaji/amicons

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - assets/fonts/vuesax/
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  uses-material-design: true
  fonts:
    - family: lucide
      fonts:
        - asset: assets/fonts/lucide/lucide.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
    - family: iconly
      fonts:
        - asset: assets/fonts/iconly/iconly.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
    - family: remix
      fonts:
        - asset: assets/fonts/remix/remix.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
    - family: flaticon
      fonts:
        - asset: assets/fonts/flaticon/flaticon.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
    - family: vuesax
      fonts:
        - asset: assets/fonts/vuesax/vuesax.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic


  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
